### PR TITLE
Override context tarball name

### LINKED ISSUE #225: Override context tarball name
Context tarball is currently fixed to `context.tar.gz`.
It would be useful to pass this name as an argument. Especially for running multiple build in parallel.

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #225

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
Thanks @priyawadhwa! So I can close this PR, right?
When is there a new release of kaniko? :-)

**Comment by priyawadhwa** [comment]
Yah you can go ahead and close it -- I'll probably release it today or Monday, I just want to get this bug fix merged! (#228 )

**Comment by priyawadhwa** [comment]
Hey @dgageot, I just released a new version of kaniko :)

**Comment by dgageot** [comment]
@priyawadhwa Thanks! I'll use it in Skaffold right away

**Pull request closed without merging**
