### PR TITLE
Upgrade aws go sdk for supporting eks oidc credential chain

### PR DESCRIPTION
**Pull request by ffahri**
Upgrading aws go sdk to support eks oidc for iam.
This way kaniko can use oidc service accounts to push images to ecr

https://github.com/GoogleContainerTools/kaniko/issues/826

### CODE REVIEW

**Comment by tejal29** [comment]
@ffahri Can you please sign the Google CLA

**Comment by ffahri** [comment]
@googlebot I signed it!

**Comment by ffahri** [comment]
@tejal29 some packages are removed from dep is there any more tests should i run for to make sure?

**Comment by ffahri** [comment]
im having problem with logrus due to dep check out of sync. will try to fix

**Comment by ffahri** [comment]
@tejal29 hey updated logrus to be sync with dep check. Also updated go aws sdk to latest

**Comment by tejal29** [comment]
Thanks @ffahri running our integration tests now.

**Comment by tejal29** [comment]
Looks like some integration tests failed

```
 --- FAIL: TestRun/test_Dockerfile_test_multistage (10.36s)
        integration_test.go:224: diff = [
              {
                "Image1": "gcr.io/kaniko-test/docker-dockerfile_test_multistage",
                "Image2": "gcr.io/kaniko-test/kaniko-dockerfile_test_multistage",
                "DiffType": "File",
                "Diff": {
                  "Adds": [
                    {
                      "Name": "/dockerfiles/Dockerfile_test_cache_copy",
                      "Size": 64
                    }
                  ],
                  "Dels": null,
                  "Mods": [
                    {
                      "Name": "/images.go",
                      "Size1": 10748,
                      "Size2": 10787
                    },
                    {
                      "Name": "/date",
                      "Size1": 29,
                      "Size2": 29
                    }
                  ]
                }
              },
              {
                "Image1": "gcr.io/kaniko-test/docker-dockerfile_test_multistage",
                "Image2": "gcr.io/kaniko-test/kaniko-dockerfile_test_multistage",
                "DiffType": "Metadata",
                "Diff": {
                  "Adds": [],
                  "Dels": []
                }
              }
            ]
        integration_test.go:227: []integration.diffOutput differ (-got, +want): {[]integration.diffOutput}[0].Diff.Adds:
            	-: []integration.fileDiff{{Name: "/dockerfiles/Dockerfile_test_cache_copy", Size: 64}}
            	+: []integration.fileDiff(nil)
```

**Comment by cvgw** [comment]
rebased an master and updated the change to use go modules

**Pull request merged**
