### PR TITLE
feat: can now resolves args from all stages

### LINKED ISSUE #747: Multi stage build fails when referencing a previous stage with ARG
**TLDR** `FROM <previous-stage-alias>-${SOME_ARG}`  fails Kaniko.

This issue presents a special case of #233 where the stage alias contains a reference to an `ARG`, a pattern supported by docker & BuildKit.

**Actual behavior**
A handy feature of Multistage builds is the ability to dynamically select a base stage in later stages:

```Dockerfile
ARG VARIANT

FROM scratch AS base
# Shared stuff over here...

FROM base AS base-dev
# Some dev only stuff here, like installing debugging tools.

FROM base AS base-prod
# Some prod only stuff here, like running Release builds or installing prod-only dependencies.

FROM base-${VARIANT}
# Final image dynamically selected. 
# Some final processing steps here, like ENTRYPOINT.
```
In the above example, when `VARIANT` is set to dev, the final image will inherit from `base-dev`. This pattern works great on stock Docker & BuildKit (which even skips unused branches, like `base-prod`, to speed up the build further). However, on Kaniko, the above build will fail

`VARIANT=dev`:
```
INFO[0003] Downloading base image base-dev              
2019/08/22 11:32:08 No matching credentials were found, falling back on anonymous
error building image: UNAUTHORIZED: authentication required; [map[Name:library/base-dev Action:pull Type:repository Class:]]
```
But, if we replace `FROM base-${VARIANT}` with a hardcoded `FROM base-dev`, everything is resolved correctly, though it renders the dynamic base picking useless.

So, it seems that Kaniko doesn't properly resolve stage aliases when they contain an ARG expression.

**Expected behavior**
Kaniko should correctly handle `FROM <previous-stage-name>-${SOME_ARG}` instructions.

**To Reproduce**
1. Write a Dockerfile similar to the one above
2. Attempt to build it with Kaniko (should fail)
3. Attempt to build it using `docker` (should succeed)

**Additional Information**
 - Dockerfile
    As presented in the example above.
 - Build Context
    `--build-arg VARIANT=dev`
 - Kaniko Image (fully qualified with digest)
    `gcr.io/kaniko-project/executor@sha256:78d44ec4e9cb5545d7f85c1924695c89503ded86a59f92c7ae658afa3cff5400`

### PR DESCRIPTION
**Pull request by JordanGoasdoue**
Fixes #747

**Description**

feat: can now resolves args from all stages

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

`Kaniko now resolves args from all stages`

### CODE REVIEW

**Comment by JordanGoasdoue** [comment]
@tejal29 I'm stuck here with this error on Travis CI : 
 https://travis-ci.org/github/GoogleContainerTools/kaniko/jobs/667502659?utm_medium=notification&utm_source=github status 
```
+sudo minikube start --vm-driver=none
* minikube v1.9.0 on Ubuntu 18.04
* Using the none driver based on user configuration
X The none driver requires conntrack to be installed for kubernetes version 1.18.0
Makefile:62: recipe for target 'minikube-setup' failed
make: *** [minikube-setup] Error 78
```

**Comment by JordanGoasdoue** [comment]
Something else to add @tejal29 : 

Taking this Dockerfile : 
```
ARG IMAGE="ubuntu:16.04"
ARG LAST_STAGE_VARIANT
FROM ${IMAGE} as base
RUN echo hi > /hi
FROM base AS base-dev
RUN echo dev >> /hi
FROM base AS base-prod
RUN echo prod >> /hi
FROM base-${LAST_STAGE_VARIANT}
RUN cat /hi
```
Using `Docker` 
```
docker build . -t test-build-arg --build-arg IMAGE --build-arg LAST_STAGE_VARIANT=dev
```
Will use MetaArg `ubuntu:16.04` for `ARG IMAGE` and : 
```
docker build . -t test-build-arg --build-arg IMAGE="" --build-arg LAST_STAGE_VARIANT=dev
```
Will return error because ARG `IMAGE` shouldn't be blank

On Kaniko even : 
```
docker run -v path/to/build:/build localhost:5000/executor-arg:latest --context=/build --no-push --build-arg IMAGE --build-arg LAST_STAGE_VARIANT="dev"
```
or 
```
docker run -v path/to/build:/build localhost:5000/executor-arg:latest --context=/build --no-push --build-arg IMAGE="" --build-arg LAST_STAGE_VARIANT="dev"
```
Will use MetaArg `ubuntu:16.04` for `ARG IMAGE`

 I didn't find a way to do something 100% similar because
`--build-arg IMAGE=""` and `--build-arg IMAGE` react similarely on opts.BuildArgs by adding on it `IMAGE=`

Here it would be good if `opts.BuildArgs` wouldn't take `IMAGE=` on the case we are on `--build-arg IMAGE` scenario. But it could  continue to do so on the case we are on `--build-arg IMAGE=""` scenario

This way i can then remove from the code I did here the check of empty string on opts.BuildArgs : https://github.com/GoogleContainerTools/kaniko/pull/1160/files#diff-b651d79bcb38f3023c41dfb9e42f6236R108 , and it should work same way than Docker.

What do you think ?

**Comment by tejal29** [comment]
@JordanGoasdoue Looks like there was a new minikube release yesterday. I will either pin the minikube version to 1.18 or wait for minikube team to suggest

**Comment by tejal29** [comment]
@JordanGoasdoue Can you please rebase from master.

**Comment by tejal29** [comment]
> Something else to add @tejal29 :
> 
> Taking this Dockerfile :
> 
> ```
> ARG IMAGE="ubuntu:16.04"
> ARG LAST_STAGE_VARIANT
> FROM ${IMAGE} as base
> RUN echo hi > /hi
> FROM base AS base-dev
> RUN echo dev >> /hi
> FROM base AS base-prod
> RUN echo prod >> /hi
> FROM base-${LAST_STAGE_VARIANT}
> RUN cat /hi
> ```
> 
> Using `Docker`
> 
> ```
> docker build . -t test-build-arg --build-arg IMAGE --build-arg LAST_STAGE_VARIANT=dev
> ```
> 
> Will use MetaArg `ubuntu:16.04` for `ARG IMAGE` and :
> 
> ```
> docker build . -t test-build-arg --build-arg IMAGE="" --build-arg LAST_STAGE_VARIANT=dev
> ```
> 
> Will return error because ARG `IMAGE` shouldn't be blank
> 
> On Kaniko even :
> 
> ```
> docker run -v path/to/build:/build localhost:5000/executor-arg:latest --context=/build --no-push --build-arg IMAGE --build-arg LAST_STAGE_VARIANT="dev"
> ```
> 
> or
> 
> ```
> docker run -v path/to/build:/build localhost:5000/executor-arg:latest --context=/build --no-push --build-arg IMAGE="" --build-arg LAST_STAGE_VARIANT="dev"
> ```
> 
> Will use MetaArg `ubuntu:16.04` for `ARG IMAGE`
> 
> I didn't find a way to do something 100% similar because
> `--build-arg IMAGE=""` and `--build-arg IMAGE` react similarely on opts.BuildArgs by adding on it `IMAGE=`
> 
> Here it would be good if `opts.BuildArgs` wouldn't take `IMAGE=` on the case we are on `--build-arg IMAGE` scenario. But it could continue to do so on the case we are on `--build-arg IMAGE=""` scenario
> 
> This way i can then remove the check of empty string on opts.BuildArgs I did here : https://github.com/GoogleContainerTools/kaniko/pull/1160/files#diff-b651d79bcb38f3023c41dfb9e42f6236R108 , and it should work same way than Docker.
> 
> What do you think ?

Sure, we can #1147

**Comment by tejal29** [comment]
The PR passes here https://travis-ci.org/github/GoogleContainerTools/kaniko/builds/667817048?utm_medium=notification&utm_source=github_status

**Comment by JordanGoasdoue** [comment]
Yes we could do that, but first we should see impact of such a change on the code, and yes it's definetely not urgent.

**Comment by tejal29** [comment]
re-opening for travis to pick up this PR.

**Comment by gabyx** [comment]
Has this been tested with

```
FROM alpine:latest as base
RUN echo hi > /hi

FROM base AS base-dev
ARG NAME="1234"
RUN echo "dev:: $NAME" >> /hi

FROM base-dev as base-custom
ARG NAME
RUN echo "custom:: $NAME"
RUN cat /hi
```

**Without** specifying `--build-arg NAME=...`
It should work but it does not...

**Pull request merged**
