### PR TITLE
fix function name on comment

### PR DESCRIPTION
**Pull request by geekvest**
Fixes #<issue number> _in case of a bug fix, this should point to a bug and any other related issue(s)_

**Description**

fix function name on comment

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [x] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [x] The code flow looks good. 
- [x] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Examples of user facing changes:
- kaniko adds a new flag `--registry-repo` to override registry

```

### CODE REVIEW

**Comment by geekvest** [comment]
I have sign [google-cla](https://github.com/apps/google-cla),please check again

**Comment by aaron-prindle** [comment]
Thank you for the PR here @geekvest!  I am not sure why given what you stated [here](https://github.com/GoogleContainerTools/kaniko/pull/2707#issuecomment-1695256473) but the `cla/google` check still says that you have not signed the CLA.  Perhaps you can try to sign it once more or we can wait a bit to see if it updates over time?  Unfortunately we cannot merge this PR unless the `cla/google` check passes.

**Comment by geekvest** [comment]
> Thank you for the PR here @geekvest! I am not sure why given what you stated [here](https://github.com/GoogleContainerTools/kaniko/pull/2707#issuecomment-1695256473) but the `cla/google` check still says that you have not signed the CLA. Perhaps you can try to sign it once more or we can wait a bit to see if it updates over time? Unfortunately we cannot merge this PR unless the `cla/google` check passes.

Thanks. Signed.

I modified the alias mailbox of github, and it took effect after refreshing

**Review by aaron-prindle — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
