### PR TITLE
fix checkPushPermissions by --insecure

### PR DESCRIPTION
**Pull request by cn-sunletian**
Our registry is harbor by http. When I push image, error occurred on function CheckPushPermissions. 
Even add "--insecure" that doesn't work, but add "--insecure-pull" it can pull well.So i find "push.go" an error here.

### CODE REVIEW

**Comment by abergmeier** [comment]
Have a look at https://github.com/GoogleContainerTools/kaniko/pull/663.

**Comment by cn-sunletian** [comment]
@kokoro-team plz check it

**Comment by SamyCoenen** [comment]
@priyawadhwa @sharifelgamal With the current release 0.10 I get HTTPS issues, I created my own image from @cn-sunletian fork samyco/kaniko and it works.

**Comment by cn-sunletian** [comment]
@priyawadhwa Thank you for reminding me :)

**Comment by tejal29** [comment]
@cn-sunletian can you fix the lint errors? Looking forward to get this in!

**Pull request closed without merging**
