### PR TITLE
Update ACR credential helper to enable Azure Workload Identity

### PR DESCRIPTION
**Pull request by SlavaNL**
**Description**

Bump the version of [ACR Credential helper](https://github.com/chrismellard/docker-credential-acr-env/commit/82a0ddb2758901b711d9d1614755b77e401598a1) to support [Azure Workload Identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview) for Kaniko pods

### CODE REVIEW

**Comment by imjasonh** [comment]
Nice!

Can you also bump the version that gets compiled into the code and executed when cred helpers aren't available?

https://github.com/GoogleContainerTools/kaniko/blob/fe2413e6e3c8caf943d50cf1d233a561943df1d6/go.mod#L18

**Comment by SlavaNL** [comment]
@imjasonh the version is bumped

**Review by imjasonh — APPROVED** [review]

**Comment by imjasonh** [comment]
Thanks! You'll also need to accept the Google CLA before this can be merged: https://github.com/GoogleContainerTools/kaniko/pull/2431/checks?check_run_id=12027296256

**Comment by SlavaNL** [comment]
@imjasonh for the some reasons all tests failed. What happened?

**Comment by imjasonh** [comment]
```
#48 0.424 go: inconsistent vendoring in /src:
#48 0.424 	github.com/chrismellard/docker-credential-acr-env@v0.0.0-20230304212654-82a0ddb27589: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
#48 0.424 	github.com/chrismellard/docker-credential-acr-env@v0.0.0-20220119192733-fe33c00cee21: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
#48 0.424 
#48 0.424 	To ignore the vendor directory, use -mod=readonly or -mod=mod.
#48 0.424 	To sync the vendor directory, run:
#48 0.424 		go mod vendor
```

You'll need to run `go mod vendor` from the root of the repo, and add those files to this PR as well.

**Comment by SlavaNL** [comment]
@imjasonh Done

**Review by imjasonh — APPROVED** [review]

**Comment by SlavaNL** [comment]
@imjasonh resolved merge conflicts

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
