### PR TITLE
Fix copying root

### LINKED ISSUE #960: Kaniko is stucking on copying root
**Actual behavior**
Kaniko is sucking forever when trying to save `/` (root) of previous stage
```
INFO[0007] Taking snapshot of full filesystem...        
INFO[0007] No files were changed, appending empty layer to config. No layer added to image. 
INFO[0007] Saving file / for later use
```

**Expected behavior**
Kaniko will copy `/` to the specified directory.

**To Reproduce**
```bash
mkdir -p /tmp/kaniko-bug
cd /tmp/kaniko-bug/

cat > Dockerfile <<\EOT
FROM alpine:3.11 as rootfs
RUN echo 7777

FROM alpine:3.11
COPY --from=rootfs / /sysroot/
EOT

docker run -ti --rm -v $PWD:/workspace gcr.io/kaniko-project/executor:v0.15.0 --dockerfile=Dockerfile --no-push
```

**Additional Information**
 - <details><summary>Strace log</summary>
   <pre>
   strace: Process 53577 attached with 17 threads
   [pid 53624] futex(0xc0004699c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53623] futex(0xc0004a52c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53622] epoll_pwait(4,  <unfinished ...>
   [pid 53621] futex(0xc0004a4bc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53620] futex(0xc0001164c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53619] futex(0xc0004804c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53618] futex(0xc0003b4148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53617] futex(0xc0004a4148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53616] futex(0xc000480148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53615] futex(0x3119a80, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53614] futex(0xc0001364c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53613] restart_syscall(<... resuming interrupted read ...> <unfinished ...>
   [pid 53612] futex(0xc000116148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53611] futex(0xc00006a848, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53610] restart_syscall(<... resuming interrupted read ...> <unfinished ...>
   [pid 53609] restart_syscall(<... resuming interrupted read ...> <unfinished ...>
   [pid 53577] futex(0x30fcc48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53613] <... restart_syscall resumed>) = -1 ETIMEDOUT (Connection timed out)
   [pid 53613] futex(0x30fc190, FUTEX_WAKE_PRIVATE, 1) = 1
   [pid 53609] <... restart_syscall resumed>) = 0
   [pid 53613] futex(0xc0004a4bc8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53621] <... futex resumed>)        = 0
   [pid 53613] <... futex resumed>)        = 1
   [pid 53621] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
   [pid 53613] futex(0x3100a60, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=999426204} <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53621] <... nanosleep resumed>NULL) = 0
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53621] futex(0xc0004a4bc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53609] futex(0x30fc190, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
   [pid 53613] <... futex resumed>)        = -1 ETIMEDOUT (Connection timed out)
   [pid 53613] futex(0x30fc190, FUTEX_WAKE_PRIVATE, 1) = 1
   [pid 53609] <... futex resumed>)        = 0
   [pid 53613] futex(0xc0004a4bc8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53621] <... futex resumed>)        = 0
   [pid 53613] <... futex resumed>)        = 1
   [pid 53621] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
   [pid 53613] futex(0x3100a60, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=999530745} <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53621] <... nanosleep resumed>NULL) = 0
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53621] futex(0xc0004a4bc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53609] futex(0x30fc190, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
   [pid 53610] <... restart_syscall resumed>) = -1 ETIMEDOUT (Connection timed out)
   [pid 53610] futex(0x30fc190, FUTEX_WAKE_PRIVATE, 1) = 1
   [pid 53609] <... futex resumed>)        = 0
   [pid 53610] futex(0xc0004a4bc8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53609] futex(0xc00006a848, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53610] <... futex resumed>)        = 1
   [pid 53621] <... futex resumed>)        = 0
   [pid 53611] <... futex resumed>)        = 0
   [pid 53609] <... futex resumed>)        = 1
   [pid 53621] futex(0xc0004a4bc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53611] futex(0x30fc180, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53610] futex(0x30fc180, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000} <unfinished ...>
   [pid 53611] <... futex resumed>)        = 0
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53611] futex(0xc00006a848, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53610] <... futex resumed>)        = -1 EAGAIN (Resource temporarily unavailable)
   [pid 53610] epoll_pwait(4, [], 128, 0, NULL, 0) = 0
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53610] futex(0xc00006a848, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53611] <... futex resumed>)        = 0
   [pid 53610] <... futex resumed>)        = 1
   [pid 53611] futex(0xc0004a4bc8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53621] <... futex resumed>)        = 0
   [pid 53611] <... futex resumed>)        = 1
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53621] futex(0xc0001364c8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53611] futex(0xc0003b4148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53621] <... futex resumed>)        = 1
   [pid 53618] <... futex resumed>)        = 0
   [pid 53614] <... futex resumed>)        = 0
   [pid 53611] <... futex resumed>)        = 1
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53614] futex(0x30fcc48, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53614] <... futex resumed>)        = 1
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53611] futex(0x31009e0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=29, tv_nsec=999501958} <unfinished ...>
   [pid 53577] <... futex resumed>)        = 0
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53577] futex(0xc000116148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53612] <... futex resumed>)        = 0
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53577] <... futex resumed>)        = 1
   [pid 53612] futex(0xc0004a4148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53617] <... futex resumed>)        = 0
   [pid 53612] <... futex resumed>)        = 1
   [pid 53617] futex(0xc0004699c8, FUTEX_WAKE_PRIVATE, 1) = 1
   [pid 53624] <... futex resumed>)        = 0
   [pid 53621] sched_yield( <unfinished ...>
   [pid 53617] sched_yield()               = 0
   [pid 53624] futex(0xc0004699c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53621] <... sched_yield resumed>)  = 0
   [pid 53618] futex(0xc0004699c8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53617] futex(0x3102840, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53614] futex(0xc0001364c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53612] futex(0xc000116148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53610] futex(0xc00006a4c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53624] <... futex resumed>)        = -1 EAGAIN (Resource temporarily unavailable)
   [pid 53621] futex(0x3102840, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53618] <... futex resumed>)        = 0
   [pid 53617] <... futex resumed>)        = 0
   [pid 53624] futex(0xc0001364c8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53621] <... futex resumed>)        = 0
   [pid 53618] futex(0xc0003b4148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53577] futex(0x30fcc48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53624] <... futex resumed>)        = 1
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53624] futex(0x30fc1a8, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000} <unfinished ...>
   [pid 53621] futex(0xc0004a4bc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53617] futex(0xc0004a4148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53614] <... futex resumed>)        = 0
   [pid 53614] futex(0x30fc1a8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53624] <... futex resumed>)        = 0
   [pid 53614] <... futex resumed>)        = 1
   [pid 53624] sched_yield( <unfinished ...>
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53624] <... sched_yield resumed>)  = 0
   [pid 53614] futex(0xc0001364c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53624] futex(0x30fc090, FUTEX_WAKE_PRIVATE, 1) = 0
   [pid 53624] epoll_pwait(4,  <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53624] <... epoll_pwait resumed>[], 128, 0, NULL, 824641757128) = 0
   [pid 53609] futex(0x30fc190, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
   [pid 53624] futex(0x30fc190, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53609] <... futex resumed>)        = -1 EAGAIN (Resource temporarily unavailable)
   [pid 53624] <... futex resumed>)        = 0
   [pid 53624] futex(0xc0001364c8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53609] sched_yield( <unfinished ...>
   [pid 53624] <... futex resumed>)        = 1
   [pid 53614] <... futex resumed>)        = 0
   [pid 53609] <... sched_yield resumed>)  = 0
   [pid 53624] futex(0x30fc1a8, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000} <unfinished ...>
   [pid 53614] futex(0x30fc1a8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53624] <... futex resumed>)        = -1 EAGAIN (Resource temporarily unavailable)
   [pid 53609] futex(0x30fc090, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
   [pid 53624] sched_yield( <unfinished ...>
   [pid 53614] <... futex resumed>)        = 0
   [pid 53624] <... sched_yield resumed>)  = 0
   [pid 53609] <... futex resumed>)        = -1 EAGAIN (Resource temporarily unavailable)
   [pid 53624] futex(0x30fc090, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53614] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
   [pid 53624] <... futex resumed>)        = 0
   [pid 53609] futex(0x30fc090, FUTEX_WAKE_PRIVATE, 1) = 0
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53614] <... nanosleep resumed>NULL) = 0
   [pid 53614] futex(0xc0001364c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53624] futex(0xc0004699c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53609] futex(0x30fc190, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
   [pid 53613] <... futex resumed>)        = -1 ETIMEDOUT (Connection timed out)
   [pid 53613] futex(0x30fc190, FUTEX_WAKE_PRIVATE, 1) = 1
   [pid 53609] <... futex resumed>)        = 0
   [pid 53613] futex(0xc0004699c8, FUTEX_WAKE_PRIVATE, 1) = 1
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53624] <... futex resumed>)        = 0
   [pid 53613] futex(0xc0001364c8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53624] futex(0xc0004a4148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
   [pid 53613] <... futex resumed>)        = 1
   [pid 53614] <... futex resumed>)        = 0
   [pid 53613] futex(0x3100a60, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=999325757} <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53624] <... futex resumed>)        = 1
   [pid 53617] <... futex resumed>)        = 0
   [pid 53614] futex(0xc0001364c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53617] futex(0xc0004a4148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53609] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
   [pid 53624] futex(0xc0004699c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
   [pid 53609] <... nanosleep resumed>NULL) = 0
   [pid 53609] futex(0x30fc190, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0}^C
   </pre>
   </details>

 - Kaniko Image (fully qualified with digest):

```
gcr.io/kaniko-project/executor:v0.15.0
gcr.io/kaniko-project/executor@sha256:630f263d9123266b9f5420d9bc130e6a79306dbc312e5a7d35d922df391192bb
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [X] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [X] </li></ul>|

### PR DESCRIPTION
**Pull request by kvaps**
Fixes #960

**Description**

This PR updates otiai10/copy module from v1.0.2 to v1.6.0.
Adds option to not copying ignored paths for CopyFileOrSymlink which solves two problems at once:

-   Allows copying root (/)
-   Avoid leaking docker credentials using COPY command while building the image.

It might need rebase after merging https://github.com/GoogleContainerTools/kaniko/pull/1725.
This branch includes both fixes: [`kvaps:fix-copying-root-and-ownership`](https://github.com/kvaps/kaniko/tree/fix-copying-root-and-ownership); compiled docker images:
```
ghcr.io/kvaps/kaniko-executor:v1.6.0-fix
ghcr.io/kvaps/kaniko-executor:v1.6.0-fix-debug
ghcr.io/kvaps/kaniko-warmer:v1.6.0-fix
```

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [X] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
- Add additional check for ignored files on COPY
- Support copying root (`/`) of image
```

### CODE REVIEW

**Comment by kvaps** [comment]
PR rebased to `v1.7.0`, new docker images with this change prepared:

```
ghcr.io/kvaps/kaniko-executor:v1.7.0
ghcr.io/kvaps/kaniko-executor:v1.7.0-debug
ghcr.io/kvaps/kaniko-warmer:v1.7.0
```

source code of fork in `master` branch:
https://github.com/kvaps/kaniko/

**Comment by jasondamour** [comment]
@kvaps any movement on this? Do you need help w last mile?

**Comment by aaron-prindle** [comment]
@kvaps would you be able to rebase the PR here?  Would like to get this in if possible, thanks!

**Comment by aaron-prindle** [comment]
Submitted this PR here https://github.com/GoogleContainerTools/kaniko/pull/2592 which rebases the changes here.  Closing and moving the conversation over that PR.  Feel free to re-submit, discuss, etc. if you would like to own this going in -  thanks!

**Pull request closed without merging**
