### PR TITLE
Rename `--whitelist-var-run` to `--ignore-var-run`.

### PR DESCRIPTION
**Pull request by tomprince**
**Description**

Renamve `--whitelist-var-run` to `--ignore-var-run`.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

- Rename `--whitelist-var-run` to `--ignore-var-run`.

### CODE REVIEW

**Comment by tejal29** [comment]
@tomprince instead of renaming, can we deprecate the old flag and add `--ignore-var-run` as a new flag?

**Comment by hd-deman** [comment]
the old flag and its decryption are invalid. 
if you specify `--whitelist-var-run=true` then `/var/run` will be ignored
and if you specify `--whitelist-var-run=false` then `/var/run` will not be ignored

**Comment by tomprince** [comment]
> @tomprince instead of renaming, can we deprecate the old flag and add `--ignore-var-run` as a new flag?

If I'm not mistaken, that is what the code does?

**Comment by tejal29** [comment]
@tomprince are you planning to work on this?

**Comment by hashworks** [comment]
Currently the deprecation does not work at all:
```
$ docker run gcr.io/kaniko-project/executor:v1.7.0-slim --whitelist-var-run
Error: unknown flag: --whitelist-var-run
Usage:
  executor [flags]
  executor [command]
[...]
$ docker run gcr.io/kaniko-project/executor:v1.7.0-slim --ignore-var-run
Flag --ignore-var-run has been deprecated, please use ignore-var-run instead.
Error: You must provide --destination, or use --no-push
Usage:
  executor [flags]
  executor [command]
[...]
```

Stuff like this makes our pipeline sad :(

**Review by imjasonh — APPROVED** [review]
Thanks!

**Comment by imjasonh** [comment]
Please rebase if you're still interested in submitting this change.

**Comment by olivergregorius** [comment]
Stale, can be closed IMHO.

**Pull request closed without merging**
