### PR TITLE
Add AWS ECR error message for tag Immutability

### PR DESCRIPTION
**Pull request by jaugustin**
**Description**

* This improve the new feature Tag immutability https://github.com/aws/containers-roadmap/issues/862 to make it compatible with AWS ECR immutability error message

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Examples of user facing changes:
- kaniko adds a new flag `--registry-repo` to override registry

```

### CODE REVIEW

**Comment by aaron-prindle** [comment]
Thanks for the PR here @jaugustin .  Can you rebase the PR here from @HEAD and re-submit , recently a CI/CD fix was made for test error seen

**Comment by jaugustin** [comment]
@aaron-prindle I rebased the MR

**Comment by jaugustin** [comment]
@aaron-prindle is there something else I should do ?

**Review by aaron-prindle — APPROVED** [review]
LGTM, thanks @jaugustin!

**Pull request merged**
