### PR TITLE
Fix #691 - ADD does not understand ENV variables

### LINKED ISSUE #691: ADD does not understand ENV variables
Hi,
Kaniko build is failing when i am trying add(ADD) a remote file using ENV variable. Here is a test case.

```dockerfile
FROM busybox
ENV TEST_PLAN https://raw.githubusercontent.com/GoogleContainerTools/kaniko/master/docs/testplan.md
RUN echo $TEST_PLAN
ADD $TEST_PLAN ./plan.md
```
Here is the error 
```
error building image: error building stage: lstat /workspace/https:/raw.githubusercontent.com/GoogleContainerTools/kaniko/master/docs/testplan.md: no such file or directory
```
I am using local dir `workspace` as my build context.

The above `Dockerfile` builds fine with both `docker` and `buildah`.
Am i missing something here or kaniko does not work with this instruction.

### PR DESCRIPTION
**Pull request by N4rm0**
Fixes #691 

The issue was that function ResolveEnvironmentReplacementList tries to check if value is a remote url. However, it misses the case the url is enclosed in the environment variable.

I made an additional check to fix #691, but IHMO I think it would be cleaner to remove the flag "isFilepath", and let the function ResolveEnvironmentReplacement handle the remote file url case.

### CODE REVIEW

**Comment by N4rm0** [comment]
@googlebot I signed it!

**Comment by tejal29** [comment]
Looks like the integration test failed due to-
```
Error building images: Failed to build image gcr.io/kaniko-test/docker-dockerfile_test_whitelist with kaniko command "[docker run -v /home/kbuilder/.config/gcloud:/root/.config/gcloud -v /tmpfs/tmp/171480209:/kaniko/benchmarks -v /usr/local/go/src/github.com/GoogleContainerTools/kaniko/integration:/workspace -e BENCHMARK_FILE=false executor-image -f /workspace/dockerfiles/Dockerfile_test_whitelist -d gcr.io/kaniko-test/kaniko-dockerfile_test_whitelist  -c /workspace]": exit status 1 INFO[0000] Resolved base name debian@sha256:38236c068c393272ad02db100e09cac36a5465149e2924a035ee60d6c60c38fe to debian@sha256:38236c068c393272ad02db100e09cac36a5465149e2924a035ee60d6c60c38fe 
INFO[0000] Resolved base name debian@sha256:38236c068c393272ad02db100e09cac36a5465149e2924a035ee60d6c60c38fe to debian@sha256:38236c068c393272ad02db100e09cac36a5465149e2924a035ee60d6c60c38fe 
INFO[0000] Error while retrieving image from cache: getting file info: stat /cache/sha256:38236c068c393272ad02db100e09cac36a5465149e2924a035ee60d6c60c38fe: no such file or directory 
INFO[0000] Downloading base image debian@sha256:38236c068c393272ad02db100e09cac36a5465149e2924a035ee60d6c60c38fe 
INFO[0000] Built cross stage deps: map[]                
INFO[0000] Error while retrieving image from cache: getting file info: stat /cache/sha256:38236c068c393272ad02db100e09cac36a5465149e2924a035ee60d6c60c38fe: no such file or directory 
INFO[0000] Downloading base image debian@sha256:38236c068c393272ad02db100e09cac36a5465149e2924a035ee60d6c60c38fe 
INFO[0000] Unpacking rootfs as cmd RUN mkdir -p /var/test     && mkdir -p /etc/test     && touch /var/test/testfile     && touch /etc/test/testfile     && ls -lah /var/test     && ls -lah /etc/test; requires it. 
INFO[0019] Taking snapshot of full filesystem...        
INFO[0053] RUN mkdir -p /var/test     && mkdir -p /etc/test     && touch /var/test/testfile     && touch /etc/test/testfile     && ls -lah /var/test     && ls -lah /etc/test; 
INFO[0053] cmd: /bin/sh                                 
INFO[0053] args: [-c mkdir -p /var/test     && mkdir -p /etc/test     && touch /var/test/testfile     && touch /etc/test/testfile     && ls -lah /var/test     && ls -lah /etc/test;] 
total 8.0K
drwxr-xr-x  2 root root 4.0K Sep 17 17:50 .
drwxr-xr-x 12 root root 4.0K Sep 17 17:50 ..
-rw-r--r--  1 root root    0 Sep 17 17:50 testfile
total 8.0K
drwxr-xr-x 2 root root 4.0K Sep 17 17:50 .
drwxr-xr-x 1 root root 4.0K Sep 17 17:50 ..
-rw-r--r-- 1 root root    0 Sep 17 17:50 testfile
INFO[0053] Taking snapshot of full filesystem...        
error pushing image: failed to push to destination gcr.io/kaniko-test/kaniko-dockerfile_test_whitelist:latest: UNKNOWN: Unable to write upload.
exit status 1
FAIL	github.com/GoogleContainerTools/kaniko/integration	356.172s


[ID: 5997453] Build finished after 443 secs, exit value: 1
```

**Comment by N4rm0** [comment]
@tejal29 I am not sure what cause the issue with the integration test, as I ran them without encountering the error mentioned in your log. 
I took the liberty of adding a test case in the integration test for ADD.

Could you relaunch the integration tests ?

**Comment by tejal29** [comment]
re-launching the tests.

**Pull request merged**
