### PR TITLE
Fix calculating path for copying ownership

### PR DESCRIPTION
**Pull request by kvaps**
Fixes #<issue number> _in case of a bug fix, this should point to a bug and any other related issue(s)_

**Description**

This PR:
- Fixes calculating path for copying ownership
- Enables error handling

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [X] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

### CODE REVIEW

**Comment by imjasonh** [comment]
Thanks! Can you fix the `gofmt` issue? That also snuck in before the lint checks were added.

**Comment by kvaps** [comment]
What do you mean? I have gofmt enabled by default in my editor

**Comment by imjasonh** [comment]
> What do you mean? I have gofmt enabled by default in my editor

There's an unrelated `gofmt` issue in pkg/util/tar_util_test.go, it's not your fault, but it'd be nice to get it fixed so tests pass.

If you don't feel like doing it that's fine (it's not your fault) but then I'll need to find someone else to approve my PR. 😕

**Comment by kvaps** [comment]
Ah, got it! I didn't noticed the failed pipeline

**Comment by kvaps** [comment]
please give me more time, I'll fix it tomorrow

**Comment by imjasonh** [comment]
> please give me more time, I'll fix it tomorrow

No rush, thanks for working on this!

**Comment by kvaps** [comment]
All jobs passed

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
