### PR TITLE
Fix panic in kaniko/pkg/util.mkdirAllWithPermissions

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

Fixes https://github.com/GoogleContainerTools/kaniko/issues/1657

**Description**

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Examples of user facing changes:
- kaniko adds a new flag `--registry-repo` to override registry

```

### CODE REVIEW

**Comment by zhangguanzhang** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Comment by Panlq** [comment]
@zhangguanzhang Do you know how to avoid this bug? Please.

**Comment by zhangguanzhang** [comment]
> @zhangguanzhang Do you know how to avoid this bug? Please.

I don't know

**Comment by zhangguanzhang** [comment]
> Please add tests so I can consider reviewing this.

The problem of occasion, I don't know how to write, Golang panic information fan-shaped Ying used the attribute

**Comment by imjasonh** [comment]
I think this was fixed in #1813 -- please let me know if that's not the case.

**Pull request closed without merging**
