### PR TITLE
Disable cache after first miss

### LINKED ISSUE #870: False-positive cache-hit on COPY --from
**Actual behavior**
I have a two stage docker image that first build sphinx docs and then copies it to the second nginx image:
```dockerfile
FROM python:3.7.5-alpine3.10 AS builder
RUN apk add --no-cache build-base libxml2-dev libxslt-dev graphviz
COPY requirements.txt /
RUN pip install --upgrade -r /requirements.txt
WORKDIR /build
COPY . ./
RUN make html
########################
FROM nginx:1.17.5-alpine AS runner
COPY --from=builder /build/_build/html /usr/share/nginx/html
```

I build it on Google Cloud Build using `gcr.io/kaniko-project/executor:latest` builder. 

The problem is the last copy instruction - even through generated HTML files differ from the previously built revision, kaniko still prefers to use the cached version:
```
Step #0: build succeeded.
Step #0:
Step #0: The HTML pages are in _build/html.
Step #0:
Step #0: Build finished. The HTML pages are in _build/html.
Step #0: INFO[0062] Taking snapshot of full filesystem...
Step #0: INFO[0064] Pushing layer gcr.io/xxx/docs-server/cache:cd602b7af9c972414b3241eb3a192a606755174cf665f9806155078915975932 to cache now
Step #0: INFO[0068] Saving file /build/_build/html for later use.
Step #0: INFO[0068] Deleting filesystem...
Step #0: INFO[0068] Downloading base image nginx:1.17.5-alpine
Step #0: INFO[0069] Error while retrieving image from cache: getting file info: stat /cache/sha256:b4c0378c841cd76f0b75bc63454bfc6fe194a5220d4eab0d75963bccdbc327ff: no such file or directory
Step #0: INFO[0069] Downloading base image nginx:1.17.5-alpine
Step #0: INFO[0069] Checking for cached layer gcr.io/xxx/docs-server/cache:5de22bf6a7763f10cd0ffa0592b8f51c876286a1d0f50564cf2f21bfd6262dc4...
Step #0: INFO[0069] Using caching version of cmd: COPY --from=builder /build/_build/html /usr/share/nginx/html
Step #0: INFO[0069] Skipping unpacking as no commands require it.
Step #0: INFO[0069] Taking snapshot of full filesystem...
Step #0: INFO[0070] COPY --from=builder /build/_build/html /usr/share/nginx/html
Step #0: INFO[0070] Found cached layer, extracting to filesystem
```

**Expected behavior**
Detect that stage 0 image files' have changes and discard cache for `COPY --from` directive in the stage 1.

**To Reproduce**
1. Run:
```sh
mkdir /tmp/bug; cd /tmp/bug
python3.7 -mvenv /tmp/bug-env && source /tmp/bug-env/bin/activate
mkdir docs
echo 'Sphinx==2.2.1' >> docs/requirements.txt
pip install -r docs/requirements.txt
cd docs
echo no | sphinx-quickstart -p foo -a foo -v 0.0.1 -r 0.0.1 -l en
```
Then add the above Dockerfile under `docs/`.

2. Now add it all to git, commit and trigger Cloud Build using the following step:
```yaml
steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --cache=true
      - --cache-ttl=336h  # 2 weeks
      - --context=/workspace/docs
      - --dockerfile=/workspace/docs/Dockerfile
      - --destination=gcr.io/$PROJECT_ID/docs-server:$BRANCH_NAME-$COMMIT_SHA
```
3. Change `docs/index.rst`, commit, trigger new build and see that resulting images still has the old version of the docs

**Additional Information**
 - Dockerfile - see above
 - Build Context - see above
 - Kaniko Image sha256:9c40a04cf1bc9d886f7f000e0b7fa5300c31c89e2ad001e97eeeecdce9f07a29
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

### PR DESCRIPTION
**Pull request by cvgw**
Fixes #870 
**Description**

Disable the cache after the first miss as following layers may depend on it. Kaniko already did this within a single stage, but not across stages.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Disable the cache for following stages after the first cache miss
```

### CODE REVIEW

**Comment by cvgw** [comment]
It may be easier to review the last commit separate from the others as it has a large amount of whitespace changes. Use this link to view the changes prior to the final commit https://github.com/GoogleContainerTools/kaniko/compare/master...76083d1bceab06054932892939fd81f2d25a5df8

**Comment by cvgw** [comment]
I think this will also fix #845 and #589

**Comment by mcfedr** [comment]
Not quite sure if this is what its doing - but i guess ideally the cache will be disabled from the point where the previous stage is included.

```Dockerfile
FROM a as a
RUN break-the-cache
FROM b as b
RUN something  <-- this will still be cached
COPY --from a a/file   <--here the cache is disabled
```

**Comment by mcfedr** [comment]
Also is this much the same as https://github.com/GoogleContainerTools/kaniko/pull/853 ?

**Comment by cvgw** [comment]
> Not quite sure if this is what its doing already - but i guess ideally the cache will be disabled from the point where the previous stage is included.
> 
> ```dockerfile
> FROM a as a
> RUN break-the-cache
> FROM b as b
> RUN something  <-- this will still be cached
> COPY --from a a/file   <--here the cache is disabled
> ```

@mcfedr unfortunately that is not the outcome this PR would produce (though I think what you are suggesting may be the ideal behavior). This PR would result in the following behavior
```dockerfile
  FROM a as a
  RUN break-the-cache
  FROM b as b <--here the cache is disabled
  RUN something
  COPY --from a a/file   
 ```

Without computing a full dependency tree or having behavior specific to `COPY --from` commands I think the behavior produced by this PR would be the best option. Computing a full dependency tree to produce the behavior that you illustrated would not be unreasonable but certainly a nontrivial undertaking. 

Open to other thoughts

As a side not I'm not sure I will be submitting this PR as I have an idea for what I think is a better implementation.

**Comment by abergmeier** [comment]
> Computing a full dependency tree to produce the behavior that you illustrated would not be unreasonable but certainly a nontrivial undertaking.

Somewhat surprised that Kaniko doesn't have a dependency DAG internally.

**Comment by abergmeier** [comment]
> @mcfedr unfortunately that is not the outcome this PR would produce (though I think what you are suggesting may be the ideal behavior).

Doesn't everything else defeat the purpose of multi-stage Dockerfiles? At least for us it is to a certain degree as bad as disabling caching completely.

**Comment by cvgw** [comment]
> > @mcfedr unfortunately that is not the outcome this PR would produce (though I think what you are suggesting may be the ideal behavior).
> 
> Doesn't everything else defeat the purpose of multi-stage Dockerfiles? At least for us it is to a certain degree as bad as disabling caching completely.

In your opinion it is preferable to leave caching broken (as it currently is) until a true dependency tree is implemented vs making an incremental fix that would prevent stale data from being retrieved from the cache though not producing ideal caching behavior?

**Comment by abergmeier** [comment]
> In your opinion is it preferable to leave caching broken (as it currently is) until a true dependency tree is implemented vs making an incremental fix that would prevent stale data from being retrieved from the cache though not producing ideal caching behavior?

Not arguing against that.
For us we will probably (in Cloud Build) replace Kaniko with Docker since the USP of Kaniko just went out the window.
In other words, being cache-compatible with Docker is a Prio 1 for us.

**Comment by cvgw** [comment]
> > In your opinion is it preferable to leave caching broken (as it currently is) until a true dependency tree is implemented vs making an incremental fix that would prevent stale data from being retrieved from the cache though not producing ideal caching behavior?
> 
> Not arguing against that.
> For us we will probably (in Cloud Build) replace Kaniko with Docker since the USP of Kaniko just went out the window.
> In other words, being cache-compatible with Docker is a Prio 1 for us.

Thank you @abergmeier . I appreciate that feedback and I will share it with the rest of the team to help prioritize work.

**Comment by cvgw** [comment]
Going in a different direction to fix this one

**Comment by mcfedr** [comment]
> In your opinion is it preferable to leave caching broken (as it currently is) until a true dependency tree is implemented vs making an incremental fix that would prevent stale data from being retrieved from the cache though not producing ideal caching behavior?

broken caching is clearly worse - but no caching isnt good, anyway it looks like you already found a better fix in https://github.com/GoogleContainerTools/kaniko/pull/883

**Pull request closed without merging**
