### PR TITLE
Fixes #1469 : Remove file that matches with the directory path

### LINKED ISSUE #1469: error building image: error building stage: failed to get filesystem from image: mkdir /usr/share/file/magic: not a directory
**Actual behavior**
When kaniko executor is run as a binary from another image, it fails with error
`error building image: error building stage: failed to get filesystem from image: mkdir /usr/share/file/magic: not a directory`

This issue occurs only when there is a difference in filesystem of container image and the base image of the dockerfile. Ex: /usr/share/file/magic is a directory in the base image whereas it a file in container filesystem.

Why is this happening:
While building a stage, FS is extracted in each layer from tar and gets created on the container except for the mounted directories. While extracting the FS, if there is a dir(/usr/share/file/magic) which needs to be created on the container, and there is already a file(/usr/share/file/magic) with same path on the container then an error(`not a directory`) is thrown

**Expected behavior**
Kaniko executor should not fail while creating a dir if there is already a file with the same path. 

There should be a check [here](https://github.com/GoogleContainerTools/kaniko/blob/master/pkg/util/fs_util.go#L752), if there exists a file with the dir path then it should be deleted before proceeding with the dir creation

**To Reproduce**
1. Build this dockerfile using docker and tag it as container_image, `docker build -t container_image .`
```
FROM gcr.io/kaniko-project/executor:debug as kanikoImage

FROM amazoncorretto:11

COPY --from=kanikoImage /kaniko/executor /kaniko/executor
```
2. Build below docker file using kaniko executor from above created image, `docker run -v {dockerfile_location}:/workspace container_image /kaniko/executor --dockerfile /workspace/Dockerfile --no-push --verbosity=trace`

```
FROM python:3.7.6

RUN apt-get update && \
    apt-get install -y virtualenv git default-mysql-client
```
3. Above build fails with error `error building image: error building stage: failed to get filesystem from image: mkdir /usr/share/file/magic: not a directory`

**Additional Information**
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by Anugushashank**
Fixes #1469 . 

**Description**
While extracting the FS, if there is a dir(/usr/share/file/magic) which needs to be created on the container, and there is already a file(/usr/share/file/magic) with same path on the container then an error(not a directory) is thrown

This PR handles this issue by checking if the directory already exists as a file on the container system and removes the file if it exists

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

### CODE REVIEW

**Comment by Anugushashank** [comment]
@googlebot I signed it!

**Comment by tejal29** [comment]
@Anugushashank LGTM
can you please fix the lint error and add a comment "@googlebot I fixed it"

**Comment by Anugushashank** [comment]
@googlebot I fixed it.

**Comment by anugu-chegg** [comment]
@googlebot I consent.

**Comment by tejal29** [comment]
You can run `find . -name "*.go" | grep -v vendor/ | xargs gofmt -l -s -w` to fix your gofmt issue

**Comment by Anugushashank** [comment]
Phew!! Thanks @tejal29 . Fixed everything now

**Review by tejal29 — APPROVED** [review]

**Pull request merged**
