### PR TITLE
feat: add support for client tls on a per registry basis

### PR DESCRIPTION
**Pull request by darkdragn**
Added a --registry-tls switch, using key=value style string, supporting keys [registry,cert,key] allowing multiple tls certs.

### CODE REVIEW

**Comment by darkdragn** [comment]
I signed it!

**Comment by darkdragn** [comment]
@tejal29 Sorry about the delay, it's been a busy week. I'll try adding some throughout the week, but I'll have some up by this weekend at the latest. Let me know if that time frame doesn't work, if we're trying to make it into a beta/milestone/something, and I'll do what I can to move some work around and get to it earlier.

**Comment by tejal29** [comment]
no worries @darkdragn. Thanks!

**Comment by bputt** [comment]
@darkdragn thanks for this PR, it's extremely useful  and I'd love to see it merged. Would you be able to write the tests?

**Comment by tejal29** [comment]
@bputt do you want to take this up?

**Comment by bputt** [comment]
@tejal29 I'm not a go dev, but prob could figure it out if I want this to get merged into master ;)....Can confirm it works in prod (test it live!)

**Comment by antechrestos** [comment]
@tejal29 @darkdragn this job looks grate. I am eager to take this up if needed.  It would be too bad to lose it.

**Comment by bputt** [comment]
@antechrestos feel free, it'd be much appreciated

**Comment by antechrestos** [comment]
@bputt to do so I have two scenarios

1. create another pull request with a cherry-pick of @darkdragn job

2. ask @darkdragn to make me contributor of his cloned repository

**Comment by bputt** [comment]
@antechrestos I like option 1

**Comment by antechrestos** [comment]
I would like @tejal29 's point of view. Best of all would be @darkdragn 's return :smirk:

**Comment by antechrestos** [comment]
@tejal29 @bputt in fact I've just tested it against my companies' registry that uses a self-signed certificate and found out that this change does not bring what I was looking for. Looking further, I found out that this change uses an ssl authentication and does not import the registry certificate.  I tested to use ssl authentication on gitlab registry and did not succeeded.

I am going to submit a new PR that allows user to import a registry certificate.

**Comment by antechrestos** [comment]
@darkdragn does the change brought by #1037 suits your needs? If so, could you close this PR?
Thanks.

**Comment by bputt** [comment]
@antechrestos I can test the change once you release a newer version and push it up to dockerhub

**Comment by antechrestos** [comment]
@bputt I am not a core contributor. Hence I cannot make a release.

However you may checkout the project and run a `make image` to build the image locally. Otherwise we shall wait for 0.19 to be released.

**Comment by tejal29** [comment]
@antechrestos you can make a docker image and push it docker hub if you have access to a public registry.

All you have to do is run `make images`
```
REGISTRY=<your-registry> make images
```
and then you can push the images via docker command.

**Comment by antechrestos** [comment]
@bputt #1037 was released in 0.19 and the current version is 0.22.
Can you confirm us that   your problem is solved?

@tejal29 the current change brought by this pull request was to provide a key pair of key to authenticate against a private registry?

It seems to be the analogue of [protecting the daemon socket](https://docs.docker.com/engine/security/https/) 

Because currently we already have options to provide per registry certificates option. 

@darkdragn can you confirm us that this pull request can be closed?

**Comment by tejal29** [comment]
> @bputt #1037 was released in 0.19 and the current version is 0.22.
> Can you confirm us that your problem is solved?
> 
> @tejal29 the current change brought by this pull request was to provide a key pair of key to authenticate against a private registry?
> 
> It seems to be the analogue of [protecting the daemon socket](https://docs.docker.com/engine/security/https/)
> 
> Because currently we already have options to provide per registry certificates option.
> 
> @darkdragn can you confirm us that this pull request can be closed?

Thanks @antechrestos for the explanation. Will wait for @darkdragn response.

**Comment by tejal29** [comment]
closing due to inactivity

**Pull request closed without merging**
