### PR TITLE
Update version number for release 1.5.0

### LINKED ISSUE #1583: kaniko release v1.5.0 reports as v1.3.0
**Actual behavior**
Using the command `/kaniko/executor version` in a freshly pulled docker image (e.g. `gcr.io/kaniko-project/executor:v1.5.0-debug`) outputs 1.3.0

**Expected behavior**
I'd expect that the new release 1.5.0 will report as 1.5.0.

**To Reproduce**
- pull image
- run `/kaniko/executor version`

### PR DESCRIPTION
**Pull request by hochreitercorpuls**
Fixes #1583

**Description**

Updated `MINOR`

### CODE REVIEW

**Comment by hochreitercorpuls** [comment]
@googlebot I signed it!

**Review by tejal29 — APPROVED** [review]

**Comment by tejal29** [comment]
@hochreitercorpuls can you please sign the CLA?

**Comment by hochreitercorpuls** [comment]
@googlebot I signed it!

**Comment by tejal29** [comment]
Sorry this is no longer needed.

**Pull request closed without merging**
