### PR TITLE
Set the docker default seccomp profile in the executor process.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by r2d4** [comment]
Does this technically prevent users from specifying a more restrictive seccomp profile at the pod level? Since this would technically be trying to "elevate" permissions then

**Comment by dlorenc** [comment]
> Does this technically prevent users from specifying a more restrictive seccomp profile at the pod level? Since this would technically be trying to "elevate" permissions then

Yeah, I think that would fail. That's why I added the --use-seccomp flag.

**Comment by sanmai-NL** [comment]
@dlorenc: What prevents this from being merged at this time?

**Comment by tejal29** [comment]
@dlorenc Are you still interested in merging this in?

**Comment by tejal29** [comment]
closing due to inactivity.

**Pull request closed without merging**
