### PR TITLE
Support for private registries in the cache warmer

### LINKED ISSUE #503: Warmer does not work with private images
**Actual behavior**
I have a pod running the cache warmer. It has multiple --image arguments. The public images download just fine but the rest silently fail. I have made sure the docker config is mounted at /kaniko/.docker/config.json and the DOCKER_CONFIG environment variable is set to /kaniko/.docker/

**Expected behavior**
Should use the credentials specified to download the private image.

**To Reproduce**
1. Create a pod with for the cache warmer. Make sure there are some private images. In the list of images. Make sure that the docker config is properly mounted. 
2. See that the private image was not downloaded

**Additional Information**
Using gcr.io/kaniko-project/warmer:latest

### PR DESCRIPTION
**Pull request by stijndehaes**
Closes #503

Signed-off-by: Stijn De Haes <stijndehaes@gmail.com>

**Description**

Adds support for private registries to the cache warmer

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Added support for private registries to the cache warmer.

```

### CODE REVIEW

**Comment by stijndehaes** [comment]
Not sure on how to best write tests for this, if anyone could give me some pointers that would be great :)

**Comment by cvgw** [comment]
@stijndehaes with some of the recent changes to master there are some conflicts in `pkg/cache/warm.go` that need to be resolved with your new code. 

Specifically, the call to `remote.Image` is now done inside of the method `Warm` and `remote.Image` is passed as an argument.

One possible solution would be to add a new field on the struct `Warmer`; something like `RemoteOptions`.

Another option could be to wrap `remote.Image` in an anonymous method which will pass `ropts`.

I'm happy to help out.

**Comment by tejal29** [comment]
@stijndehaes would love to get this in! Let us know how we can help.

**Comment by stijndehaes** [comment]
@tejal29 @cvgw I will try to fix the conflicts this week! Thank you for the reminder :)

**Comment by stijndehaes** [comment]
Ok fixed the conflicts and retested with ECR. Everything is working :)

**Comment by tejal29** [comment]
Thanks @stijndehaes. running kokoro tests and will try to merge this in today.

**Comment by cvgw** [comment]
Thanks @stijndehaes 👍

**Pull request merged**
