### PR TITLE
Release v1.9.0

### PR DESCRIPTION
**Pull request by chuangw6**
# Release v1.9.0
**Highlights**
- #2049
- #2054
- #2047
- #2066
- #2089
- #2047
- #2040
- and a number of dependency bumps

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Releasing v1.9.0
```

### CODE REVIEW

**Comment by msuperina** [comment]
Hi @chuangw6 I was wondering:
- is this the next planned release ?
- would https://github.com/GoogleContainerTools/kaniko/pull/2106 be part of it ? If not do you know why and when would it be released ?
Thanks in advance

**Comment by chuangw6** [comment]
> Hi @chuangw6 I was wondering:
> 
> * is this the next planned release ?
> * would [fix: getUIDandGID is able to resolve non-existing users and groups #2106](https://github.com/GoogleContainerTools/kaniko/pull/2106) be part of it ? If not do you know why and when would it be released ?
>   Thanks in advance

Hi @msuperina ,
- #2115 is tracking the release. Depending if we want to pick up some hot fixes, unfortunately, I am not sure exactly when.
- sure. Everything in the latest main will be included in the next release.

**Comment by zzh8829** [comment]
Hi any target date for the release? we are currently using HEAD commit build in production which is not very desirable.

**Comment by chuangw6** [comment]
@imjasonh Please take a look. Let me know if we want to highlight more features/fixes. Thanks

**Review by imjasonh — APPROVED** [review]

**Comment by chuangw6** [comment]
> Hi any target date for the release? we are currently using HEAD commit build in production which is not very desirable.

Hi @zzh8829 
we just made the release. 🎉  Thanks for checking in.

**Pull request merged**
