### PR TITLE
Stop caching COPY layers

### LINKED ISSUE #1357: Why are `COPY` layers cacheable?
The [README says](https://github.com/GoogleContainerTools/kaniko/blob/0c71a1bb0ea1eb619ea369a72cd0d6763790aa3f/README.md#caching-layers) that only `RUN` layers are cacheable.  But last year `COPY`s were also made cacheable 
 in https://github.com/GoogleContainerTools/kaniko/commit/dbabcb1f5fc101c2735c9438cf326e8a8a51aac4 (cc @donmccasland).

I'm not an expert in docker, but it's not clear at face value why you'd want to cache such layers.  If you're `COPY`ing some data in, you already have it locally, right?  But when layer caching is enabled with a remote repository, instead of just executing that local copy, you hash that local data, then go to the network to download a layer containing the same data.  Or, upon a miss, you spend time pushing the layer to your cache.

We have a performance-sensitive image build using Kaniko that has a few `RUN`s that we'd like cached, and some large `COPY`s that, being cached, are actually offsetting performance improvements from caching `RUN`s.  And our image cache is much larger than we'd like.

@donmccasland can you clarify the intent of cacheable `COPY`s?  And would you be receptive to a PR adding a flag to disable caching for `COPY` commands?

Thanks for your time!

### PR DESCRIPTION
**Pull request by isker**
Resolves #1357

**Description**

Cached COPY layers are expensive in that they both need to be retrieved over the network and occupy space in the layer cache.

They are unnecessary in that we already have all resources needed to execute the COPY locally, and doing so is a trivial file-system operation.  This is in contrast to RUN layers, which can do arbitrary and unbounded work.

The end result is that cached COPY commands were more expensive when cached, not less.  Remove them.

**Submitter Checklist**

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

- kaniko no longer caches `COPY` commands in its layer cache as the associated network and storage costs outweigh the costs of executing them locally.

### CODE REVIEW

**Comment by isker** [comment]
Sorry, couldn't get all of the tests to run on my macbook so I decided to "test in CI".  Clearly not working.  The tests run as expected on a Linux box, will fix them there.

**Comment by isker** [comment]
I think that integration test that failed is flakey?  It was not failing previously.

**Comment by tejal29** [comment]
> Unit tests are good to go now, I removed some obsolete test cases and added a new one.
> 
> I think that integration test that failed is flakey? It was not failing previously.

Thanks @isker i restarted the failed integration test. I opened a issue to look into flaky test #

**Comment by tejal29** [comment]
@isker If a file in the copy command changes, then the Run command will be invalidated since the composite key for the previous COPY  layer will be different.
e.g. in the below dockefile,
```
FROM ...

COPY package.json package-lock.json ./
RUN npm ci 
```

The cache key for `RUN npm ci ` depends on contents of file copied `COPY package.json package-lock.json ./`
If contents change the cache will change and hence `Run npm ci` will be executed locally.

**Review by tejal29 — COMMENTED** [review]
code change looks good.
Pending Manual Verification

**Comment by isker** [comment]
Hi @tejal29, anything else you need me to do here?

**Comment by tejal29** [comment]
Verified this is working on my build.

**Comment by tejal29** [comment]
Sorry for the delay @isker 
This will be part of v1.2.0 release of kaniko.

**Comment by isker** [comment]
No worries.  Thank you!

**Comment by tejal29** [comment]
@isker did you end up testing v1.2.0?

**Comment by isker** [comment]
@tejal29 have not had time yet to do so but I will let you know the results when I do.

**Comment by tejal29** [comment]
sounds good. no one has reported issues yet!

**Comment by isker** [comment]
@tejal29 with Kaniko 1.2.0, we're seeing the improvements we expect.  Before, it took the same amount of time to build our image with caching on as with it off, because we were stuck downloading and uploading large COPY layers, with the added cost of maintaining the layer cache with caching on.

Afterward, we see a 30-40% improvement in build time with caching on, and of course our layer cache is smaller.

Thanks for your support on getting this merged and released!

**Comment by tejal29** [comment]
Thanks @isker

**Pull request merged**
