### PR TITLE
Fix support for insecure registry

### LINKED ISSUE #168: Flag --insecure-skip-tls-verify has no effect
Caused by PR https://github.com/GoogleContainerTools/kaniko/pull/140

### PR DESCRIPTION
**Pull request by guilhermebr**
fixes #168

### CODE REVIEW

**Comment by guilhermebr** [comment]
This PR needs one go-containerregistry change to be merged

**Comment by dlorenc** [comment]
@guilhermebr are you still planning on fixing this?

**Comment by guilhermebr** [comment]
@dlorenc Yes I will back this week to solve this! sorry for the delay

**Comment by StephenLiuYa** [comment]
I'm looking forward to this.

**Comment by shashankkoppar** [comment]
Is there any progress on this one?

**Comment by alexmojo** [comment]
Any updates?

**Comment by guilhermebr** [comment]
Waiting for https://github.com/google/go-containerregistry/pull/125

**Comment by diclophis** [comment]
You can install your own set of root-certificates and volume map them into the kaniko deployment as a possible alternative to using HTTP or ignoring bad SSL...

```
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
spec:
  containers:
  - image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: IfNotPresent
    name: kaniko-build
    args: [...]
    volumeMounts:
    - mountPath: /kaniko/ssl/certs
      name: ca-certificates
  restartPolicy: Never
  volumes:
  - configMap:
      name: ca-certificates
    name: ca-certificates
...
```

I extract my CA authorities from a known good source, and then build a configmap mentioned above:

`kubectl create configmap ca-certificates --from-file=ca-certificates.crt --from-file=ca.private.crt`

For example, the ca trust chain is typically found on `FROM ubuntu:bionic-20180526` at `/etc/ssl/certs/ca-certificates.crt` ...

**Comment by dlorenc** [comment]
> Waiting for google/go-containerregistry#125
> 
>  👍 3

I think the change got into go-containerregistry now, still interested in porting it over here now?

**Comment by amithapa** [comment]
When is this issue going to be resolved?

**Comment by guilhermebr** [comment]
PTAL @dlorenc

**Pull request merged**
