### PR TITLE
DEMO DONT MERGE

### PR DESCRIPTION
**Pull request by cvgw**
execute demo with `./test_830.sh`

Notice that script prints `it is a dir` because `/usr/share/bug/systemd` is a dir on the base image
Notice that the go program fails because `/usr/share/bug/systemd` is not recognized as a dir in the tar

```

6087:INFO[0004] First found it /usr/share/bug/systemd FileInfo {0xc000a5f0a0} Mode -rwxr-xr-x IsDir false 
6088:INFO[0004] found it /usr/share/bug/systemd FileInfo {0xc000a5f0a0} Mode -rwxr-xr-x IsDir false 
6089:DEBU[0004] creating file /usr/share/bug/systemd         
18194:INFO[0005] First found it /usr/share/bug/systemd FileInfo {0xc00128c7e0} Mode drwxr-xr-x IsDir true 
18195:INFO[0005] found it /usr/share/bug/systemd FileInfo {0xc00128c7e0} Mode drwxr-xr-x IsDir true 
18196:TRAC[0005] creating dir /usr/share/bug/systemd          
18199:INFO[0005] something exists at path /usr/share/bug/systemd IsDir %!b(bool=false) Mode 493 
18200:INFO[0005] couldn't read /usr/share/bug/systemd, readdirent: not a directory 
18201:error building image: error building stage: error extracting file: mkdirAllWithPermissions Couldn't create directory at path /usr/share/bug/systemd: error making directory: mkdir /usr/share/bug/systemd: not a directory
```

### CODE REVIEW

**Comment by tejal29** [comment]
@cvgw Is this with `cache` or without `cache`?

**Comment by cvgw** [comment]
> @cvgw Is this with `cache` or without `cache`?

Without caching.

This was executed with `executor --context=/context --dockerfile=/context/path/to/dockerfile --destination=user/private-repo:kaniko-830`

**Comment by tejal29** [comment]
@cvgw, so i saved the `debian:jessie-slim`  locally
```
docker save debian:jessie-slim -o test.tar
tar -xvf test.tar
cd f392d84bd5e9f2864cf707d7a5b037f2c54446d8ba678b173d10f5f796469d15
tar -tf layer.tar | grep 'usr\/share\/bug\/systemd'
usr/share/bug/systemd
``

Looks like in `layer.tar` the `usr/share/bug/systemd` is a file.

I was not able to reproduce your case where, `/usr/share/bug/systemd` was found as a dir.
Here is my output
```
tejaldesai@@kaniko (u/cgwippern/830_dir_demo)$ ./test_830.sh 
Sending build context to Docker daemon  141.4MB
Step 1/2 : FROM debian:jessie-slim
 ---> 4a755ab5a0de
Step 2/2 : RUN set -x   && apt-get -y update   && echo '\nAPT::Install-Recommends "false";\nAPT::Install-Suggests "false";\n' >> /etc/apt/apt.conf   && echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list   && apt-get -o Acquire::Check-Valid-Until=false -y update   && apt-get -y -q dist-upgrade   && apt-get -y -t jessie-backports install systemd   && apt-get clean   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f30c5b7196b3
Successfully built f30c5b7196b3
Successfully tagged 830-base:latest
it is a dir
INFO[0000] Resolved base name debian:jessie-slim to debian:jessie-slim 
There are 1 stages
working on stage 0
INFO[0000] Downloading base image debian:jessie-slim    
WARN[0000] Error detecting container runtime. Using default keychain: container runtime could not be found 
INFO[0001]  Layer 0                                     
INFO[0002] First found it /usr/share/bug/systemd FileInfo {0xc000f510a0} Mode -rwxr-xr-x IsDir false 
INFO[0002] found /usr/share/bug/systemd at /usr/share/bug/systemd 
tejaldesai@@kaniko (u/cgwippern/830_dir_demo)$ 

```

**Comment by tejal29** [comment]
I compared, the two images 
1. built with docker using
 ```
docker build . -f Dockerfile.base
Sending build context to Docker daemon  141.4MB
Step 1/2 : FROM gcr.io/tejal-test/830-base
 ---> f30c5b7196b3
Step 2/2 : env test 1
 ---> Using cache
 ---> b41d416f0f95
Successfully built b41d416f0f95
docker tag b41d416f0f95 gcr.io/tejal-test/docker_830
```
2. Built by kaniko using:
```
./run_in_docker.sh Dockerfile.base ~/go/src/github.com/GoogleContainerTools/kaniko gcr.io/tejal-test/830

INFO[0000] Resolved base name gcr.io/tejal-test/830-base to gcr.io/tejal-test/830-base 
INFO[0000] Resolved base name gcr.io/tejal-test/830-base to gcr.io/tejal-test/830-base 
INFO[0000] Downloading base image gcr.io/tejal-test/830-base 
INFO[0001] Error while retrieving image from cache: getting file info: stat /cache/sha256:63e775e9040b1ff4b9bdd9568fe134c86a8e0d1a6d8f31de7556be3a4f189139: no such file or directory 
INFO[0001] Downloading base image gcr.io/tejal-test/830-base 
INFO[0001] Built cross stage deps: map[]                
INFO[0001] Downloading base image gcr.io/tejal-test/830-base 
INFO[0002] Error while retrieving image from cache: getting file info: stat /cache/sha256:63e775e9040b1ff4b9bdd9568fe134c86a8e0d1a6d8f31de7556be3a4f189139: no such file or directory 
INFO[0002] Downloading base image gcr.io/tejal-test/830-base 
INFO[0002] Unpacking rootfs as cmd RUN echo $HOME requires it. 
error building image: error building stage: mkdir /usr/share/bug/systemd: not a directory
```

shows an error as described in #830

**Comment by julienvey** [comment]
Do you know of any workaround for this issue ?

**Comment by cvgw** [comment]
> Do you know of any workaround for this issue ?

@julienvey unfortunately no. We will be sure to share any work arounds we find in the linked issue. Working on finding a solution.

**Comment by tejal29** [comment]
closing due to inactivity.

**Pull request closed without merging**
