### PR TITLE
Set image platform for any build

### LINKED ISSUE #997: Kaniko doesn’t set image platform for FROM scratch images
**Actual behavior**
When trying to pull an image generated with kaniko `FROM scratch` with podman, podman complains:
```
Trying to pull registry.tld/package-builder...
  Image operating system mismatch: image uses "", expecting "linux"
Error: unable to pull registry.tld/package-builder: unable to pull image: Image operating system mismatch: image uses "", expecting "linux"
```
Apparently, the platform is set only for images derived from others:
```
$ skopeo inspect docker://registry.tld/debian-based-image-builder | grep Os
    "Os": "linux",
$ skopeo inspect docker://registry.tld/package-builder | grep Os
    "Os": "",
```
**Expected behavior**
Set the platform value to an actual one or provide a way to override.

**To Reproduce**
```
FROM scratch

ADD rootfs.tar.gz /
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by Vlatombe**
Fixes #997 .
 Downstream of https://github.com/google/go-containerregistry/pull/693 for `--reproducible` to keep os/arch set.

**Description**

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
- Set image platform (os/arch) for any build
```

### CODE REVIEW

**Comment by Vlatombe** [comment]
Anything holding this?

**Comment by tejal29** [comment]
Sorry @Vlatombe for the delay. Would you be able to merge this with latest master and i can merge this in for next release.

**Comment by Vlatombe** [comment]
Reverted module update since https://github.com/GoogleContainerTools/kaniko/pull/1146 picked it up.

**Comment by Vlatombe** [comment]
@tejal29 done.

**Pull request merged**
