### PR TITLE
pkg: prepend library when using registry mirror

### LINKED ISSUE #1172: When `--cache true` and `--registry-mirror ...` kaniko cannot find manifest
**Actual behavior**
When running the docker kaniko debug image with `--cache true` and `--registry-mirror ...` 
 kaniko throws error about not being able to find the manifest of the base image. 

This works if `library/` is added to the base image name in the `FROM` line, in the Dockerfile. This shouldn't be required?
 
Error output:
```
INFO[0000] Resolved base name ubuntu:xenial to ubuntu:xenial 
 INFO[0000] Resolved base name ubuntu:xenial to ubuntu:xenial 
 INFO[0000] Retrieving image manifest ubuntu:xenial      
 ERRO[0000] Error while retrieving image from cache: ubuntu:xenial MANIFEST_UNKNOWN: manifest unknown; map[Tag:xenial] 
 INFO[0000] Retrieving image manifest ubuntu:xenial      
 error building image: MANIFEST_UNKNOWN: manifest unknown; map[Tag:xenial]
```

**Expected behavior**
Docker image should be built assuming `library/` for the base image, unless otherwise specified. 

**To Reproduce**
1. Set both `--cache true` and `--registry-mirror ...` on a build 
2. Build an image who's base `FROM` line does NOT specify `library/` in the image name.
3. Build fails with `manifest unknown`.

**Additional Information**
Failed gitlab pipeline: 
https://git.cs.sun.ac.za/Computer-Science/docker-prebuild/sun-ubuntu/-/jobs/226756

Working pipeline after adding `library/...` to dockerfile `FROM` line.
https://git.cs.sun.ac.za/Computer-Science/docker-prebuild/sun-ubuntu/-/jobs/226767

Example repo with dockerfile and .gitlab-ci.yml:
https://git.cs.sun.ac.za/Computer-Science/docker-prebuild/sun-ubuntu
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by greut**
Fixes #1172

**Description**

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
- fixes image name when using `registry-mirror` so `library/` is inferred
```

### CODE REVIEW

**Comment by greut** [comment]
was #1261

**Comment by tejal29** [comment]
@greut Can you please add some tests?

**Comment by greut** [comment]
@tejal29 what do I get?

**Comment by zhangfei9734** [comment]
The same question, any progress?

**Comment by tejal29** [comment]
@greut and @zhangfei9734 sorry for the delay. 
Merged the tests

**Comment by tejal29** [comment]
> @tejal29 what do I get?

@greut please see our contribution guidelines #Contribution guidelines and our PR template https://github.com/GoogleContainerTools/kaniko/blob/master/.github/pull_request_template.md. 

In order to add maintainability and avoid future regressions, unit tests are good.

**Comment by greut** [comment]
@tejal29 Thanks mate!

**Pull request merged**
