### PR TITLE
upgrade go container registry to latest master

### LINKED ISSUE #1144: Pick up latest GGCR
The latest version of GGCR has a fix to k8schain to support ECR on AWS.

I poked at this a little and my `go mod` fu is not strong enough yet to figure things out.  It seems a number of dependencies (e.g. K8s) are pretty far behind, and should probably be bumped too.

cc @jonjohnsonjr @tejal29 

If you have a build of kaniko you'd like me to try out on AWS/EKS with ECR, I'd be happy to take if for a spin 😇

### PR DESCRIPTION
**Pull request by tejal29**
Fixes #1144

Ran 
```
go get -u github.com/google/go-containerregistry
go mod tidy
```

### CODE REVIEW

**Comment by tejal29** [comment]
@mattmoor Feel free to build the kaniko executor image with the instructions below to proceed with your testing.

```
REGISTRY=<you registry> make images
```

**Comment by mattmoor** [comment]
Things look kinda broken.  Should I wait?

**Comment by tejal29** [comment]
> Things look kinda broken. Should I wait?

yep sorry, i missed to add the `vendor/modules.txt` changes.

**Comment by tejal29** [comment]
hmm @samos123 have you seen this failure before https://travis-ci.org/github/GoogleContainerTools/kaniko/jobs/664165999?utm_medium=notification&utm_source=github_status?

**Comment by samos123** [comment]
it shouldn't have run K8s tests in that test run, for some reason the TestK8s wasn't excluded correctly. I'm looking into it more.

**Comment by samos123** [comment]
It's weird, this PR worked fine and also ran K8s tests separately: https://travis-ci.org/github/GoogleContainerTools/kaniko/builds/664580845?utm_source=github_status&utm_medium=notification. So not sure what's different here and why -list=Test is not returning the correct output...

**Comment by samos123** [comment]
I restarted that specific job and it now succeeded, for some reason the make integration-test-misc script ran all tests instead of only the misc tests and I still don't know why.

**Comment by mattmoor** [comment]
@tejal29 if this is ready for me to try out, I will do that tomorrow?

**Comment by mattmoor** [comment]
@tejal29 tl;dr success!

I built this image and copied it to `docker.io/mattmoor/kaniko:tejal` and ran it via the Tekton task on EKS with the following setup:
```
# Cluster must have oidc enabled:
eksctl utils associate-iam-oidc-provider --name knative-aws --approve

# Create service account with:
eksctl create iamserviceaccount \
  --name builder \
  --namespace default \
  --cluster knative-aws \
  --attach-policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser \
  --approve
```

I then ran the Tekton TaskRun as the service account `builder` that the above creates, and it worked great!

**Comment by tejal29** [comment]
great Thanks @mattmoor. I will probably release this in v0.20.0 and let you know when its released.

**Comment by mattmoor** [comment]
Perfect, thanks!

**Comment by mattmoor** [comment]
Maybe worth a PR to the tekton Catalog when that comes out? https://github.com/tektoncd/catalog/issues/235

**Pull request merged**
