### PR TITLE
Enable overwriting of links (solves #351)

### PR DESCRIPTION
**Pull request by xanonid**

### CODE REVIEW

**Comment by priyawadhwa** [comment]
Hey @xanonid, thanks for contributing this fix! Could you add `Dockerfile_test_extraction` in the [dockerfiles](https://github.com/GoogleContainerTools/kaniko/tree/master/integration/dockerfiles) directory so that our integration tests can make sure extraction works for this image?

A simple Dockerfile:

```
FROM docker.elastic.co/kibana/kibana@sha256:e61c1122d9bc8dc8a113c79a035cf3c34d09674685f550ec842afc2d923ad568
```
should suffice.

**Comment by xanonid** [comment]
@sharifelgamal Seems like the kokoro check did not run again. Is there something I can do?

**Comment by dlorenc** [comment]
I'll try poking kokoro...

**Comment by dlorenc** [comment]
The test failure is:

```shell
    		]time="2018-09-21T07:44:27-07:00" level=warning msg="remove /tmpfs/tmp/gcr.iokaniko-testkaniko-dockerfile_test_replaced_hardlinks081715982/root/.bash_profile: permission denied"
    		time="2018-09-21T07:44:28-07:00" level=warning msg="remove /tmpfs/tmp/gcr.iokaniko-testdocker-dockerfile_test_replaced_hardlinks989545749/root/.bash_profile: permission denied"
```

which looks like an issue with the base image and container-diff.

I'll look into it a bit...

**Comment by dlorenc** [comment]
Is there any way you could reproduce this with a simpler base image than:

docker.elastic.co/kibana/kibana@sha256:e61c1122d9bc8dc8a113c79a035cf3c34d09674685f550ec842afc2d923ad568

**Comment by xanonid** [comment]
@dlorenc I replaced the test image. Hopefully, this works better. Could you trigger kokoro again if necessary, please?

**Comment by rroller** [comment]
I can confirm that this change corrects the issue below... (I've tested it with one of my builds and it works fine now)

This is the error prior to applying the change in this PR:
```bash
INFO[0000] Downloading base image gcr.io/google-appengine/openjdk:8 
INFO[0000] Mounted directories: [/kaniko /var/run /etc/mtab /proc /dev /dev/pts /sys /sys/fs/cgroup /sys/fs/cgroup/systemd /sys/fs/cgroup/cpuset /sys/fs/cgroup/blkio /sys/fs/cgroup/freezer /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/devices /sys/fs/cgroup/pids /sys/fs/cgroup/rdma /sys/fs/cgroup/memory /sys/fs/cgroup/net_cls,net_prio /sys/fs/cgroup/perf_event /sys/fs/cgroup/hugetlb /dev/mqueue /source /containers /dev/termination-log /etc/resolv.conf /etc/hostname /etc/hosts /dev/shm /run/secrets/kubernetes.io/serviceaccount /proc/bus /proc/fs /proc/irq /proc/sys /proc/sysrq-trigger /proc/kcore /proc/timer_list /sys/firmware] 
INFO[0000] Extracting layer 0                           
error building image: error building stage: link /bin/gunzip /bin/uncompress: file exists
```

**Comment by xanonid** [comment]
@dlorenc kokoro seemed to fail again 😞. Probably the base image was not different enough to the last? Is there another way than simple try-and-error?

**Comment by priyawadhwa** [comment]
Hey @xanonid, I looked into the failing test and I think I've fixed the issue in #363. Once that merges you can rebase and we can rerun kokoro, which I think should work at that point.

**Comment by xanonid** [comment]
@priyawadhwa Thanks - great news. BTW, I added another commit which fixes problems, if symlinks are replaced by normal files.

**Comment by priyawadhwa** [comment]
@xanonid awesome, I just merged #363 so if you rebase we can rerun the tests.

**Comment by xanonid** [comment]
@priyawadhwa I rebased the commits.

**Comment by xanonid** [comment]
@dlorenc The Kokoro run was successful 👍

**Comment by dlorenc** [comment]
Woohoo!

**Comment by rroller** [comment]
Just confirming, this PR did fix my issues.

`FROM gcr.io/kaniko-project/executor:59cb0ebec969fde3f8c8c7c9468d50580eb1e1ac`

Thanks!

**Comment by yurrriq** [comment]
This issue is now solved for us too, but https://github.com/GoogleContainerTools/kaniko/issues/245 is still a blocker.

**Pull request merged**
