### PR TITLE
fix: change the name of the acr cred helper

### LINKED ISSUE #1455: Kaniko failing to push to ECR
**Actual behavior**
Trying to push to ECR with Kaniko on Gitlab on Kubernetes and get a user denied with the node instance role as the user even when providing access and secret keys with the credstore.

**Expected behavior**
images pushes to ECS

**To Reproduce**
$ echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$AWS_DOCKER_URL\":\"ecr-login\"}}" > /kaniko/.docker/config.json
$ /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $DOCKER_REPOSITORY:$CI_COMMIT_SHORT_SHA --build-arg NPM_TOKEN=$NPM_TOKEN --skip-unused-stages=true
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "[MASKED].dkr.ecr.us-east-1.amazonaws.com/[MASKED]:b263001f": POST https://[MASKED].dkr.ecr.us-east-1.amazonaws.com/v2/[MASKED]/blobs/uploads/: DENIED: User: arn:aws:sts::[MASKED]:assumed-role/[MASKED]-NodeInstanceRole/i-[MASKED] is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:us-east-1:[MASKED]:repository/[MASKED]
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [X] </li></ul>|

### LINKED ISSUE #1864: Kaniko fails to push to ACR
**Actual behavior**

Few months back, kaniko image in Jenkins X catalog was updated to 1.6.0+, and this broke pushing images to ACR (Azure container registry) from JX pipelines.
The reason is that the acr cred helper executable name is different in kaniko image.
It should be `docker-credential-acr-env` instead of `docker-credential-acr`
If we locally install https://github.com/chrismellard/docker-credential-acr-env, then the executable is `docker-credential-acr`
In Jenkins X, we set the cred helper value to acr-env, so kaniko searches for an execitable `docker-credential-acr-env` and since it's unable to find it, it returns an error:
```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "XXXXX.azurecr.io/jx3rocks/node-http-aks02:0.0.2": resolving authorization for XXXXX.azurecr.io failed: error getting credentials - err: exec: "docker-credential-acr-env": executable file not found in $PATH
```

**Expected behavior**
Kaniko pushes the image to ACR.

**To Reproduce**
1. Upgrade version of kaniko from 1.3.0 to 1.6.0
2. Push an image to acr registry from kaniko

**Additional Information**
 So, we set this in the dockerconfigjson file in Jenkins X/Tekton pipelines:
```
{ 
 "credHelpers" : {
   "XX":"acr-env"
 }, 
...
}
```

This value (`acr-env`) along with the suffix `docker-credential-` (https://github.com/docker/cli/blob/fe93451cf7d26fd211c4f4c2f55d32022294b628/cli/config/credentials/native_store.go#L10) is used to find out the program that is executed by kaniko to retrieve docker credentials for the registry (https://github.com/docker/cli/blob/fe93451cf7d26fd211c4f4c2f55d32022294b628/cli/config/credentials/native_store.go#L25).

So, in case of ACR, it tries to find the executable with name `docker-credential-acr-env` instead of `docker-credential-acr`, which leads to the issues.

1.3.0 is the last version that worked.

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

fixes #1864 

**Description**

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Fix issues with kaniko unable to push images to Azure Container registry. 
```

### CODE REVIEW

**Review by imjasonh — APPROVED** [review]
Thanks!

This indicates the lack of an integration test that exercises the ACR cred helper 🤔

**Comment by ankitm123** [comment]
For integration testing, wont this require an azure cluster? We dont have one for Jenkins X atm, which is the reason we caught it late. Are there tests for ecr/gcp that I can take a look at? I did not see them in the integration folder ...

**Comment by imjasonh** [comment]
> For integration testing, wont this require an azure cluster? We dont have one for Jenkins X atm, which is the reason we caught it late. Are there tests for ecr/gcp that I can take a look at? I did not see them in the integration folder ...

Ideally yes, but that's probably going to be a nightmare to manage and setup and maintain auth for. Short of that, a test that just trivially called the helper with `--help` would have caught this bug. That wouldn't catch real auth bugs, but it's better than nothing.

This change lgtm and we should merge it, but I'd love to have better smoke tests for this in a future PR.

**Comment by ankitm123** [comment]
I guess we can just make it run the help command, that should prevent this issue in the future, wdyt?

**Pull request merged**
