### PR TITLE
feat: Add https tar.gz remote source for context

### PR DESCRIPTION
**Pull request by jfrabaute**
**Description**

Add remote https tar.gz source for the context.
The context could be on a remote tar.gz file accessible through an https server.
This is the case for example when having the source code in gerrit and using gitiles as a gerrit plugin so it's possible to get the code for an exact commit in tar.gz format.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [X ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Examples of user facing changes:
- kaniko adds a new flag `--registry-repo` to override registry

```

### CODE REVIEW

**Comment by jfrabaute** [comment]
@googlebot I signed it!

**Comment by jfrabaute** [comment]
Hi,

I didn't see there is an issue opened for this as well: https://github.com/GoogleContainerTools/kaniko/issues/1464

Thanks.

**Comment by tejal29** [comment]
@jfrabaute Can you please add the missing license header?

**Comment by jfrabaute** [comment]
> @jfrabaute Can you please add the missing license header?

Looks like you sent a fix with the license header. Sorry about that.

Thanks!

**Comment by tejal29** [comment]
no worries. Sorry, i should i have waited.

**Pull request merged**
