### PR TITLE
changing to modules from dependencies

### LINKED ISSUE #838: Upgrade from dep to gomodules for dependency management
It would be great if we upgraded to using gomodules :smile: 

https://blog.golang.org/migrating-to-go-modules

### PR DESCRIPTION
**Pull request by prary**
Fixes #838 

**Description**

changing to modules from dependencies

### CODE REVIEW

**Comment by prary** [comment]
build succeed locally with go version 1.13.3

**Comment by cvgw** [comment]
Hi @prary thanks for the PR (very happy to see this change)! I took a look at the travis failures and it looks like at least one failure was caused by the name change on the `highwayhash` pkg. It appears the vendored package still has the old name https://github.com/GoogleContainerTools/kaniko/tree/6e77b77d7ca7289593a393740eb08411d5d3acec/vendor/github.com/minio/HighwayHash

Let me know if there is anything I can do to help. Cheers

**Comment by prary** [comment]
Hi @cvgw intentionally that change is added as Highwayhash breaks with the latest go and latest highwayhash version. Hence I had uptick the golang version as well.

**Comment by cvgw** [comment]
@prary I apologize for not being more clear in my first message

I see that as part of updating kaniko to use modules the name of the `highwayhash` pkg has changed. I also see that you updated the import reference for that package.

However, it looks like the pkg in `/vendor` still has the old name `HighwayHash`. Maybe this is unrelated to why the travis build is failing, but it seemed like perhaps it could be part of the problem.

**Comment by cvgw** [comment]
These lines from the travis build are what caught my eye

```
github.com/minio/highwayhash (cannot find package "github.com/minio/highwayhash" in any of:
	/home/travis/gopath/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/minio/highwayhash (vendor tree)
	/home/travis/.gimme/versions/go1.13.3.linux.amd64/src/github.com/minio/highwayhash (from $GOROOT)
	/home/travis/gopath/src/github.com/minio/highwayhash (from $GOPATH)) and 827 more errors: run `golangci-lint run --no-config --disable-all -E typecheck` to see all errors `
```

**Comment by cvgw** [comment]
@prary  when I checkout your branch locally and run `go mod vendor` there are a lot of updates to the `vendor` directory. Should those be checked in?

I also noticed that `golangci-lint` (which runs in travis) might need to be upgraded.
From their https://github.com/golangci/golangci-lint#faq
`go1.12+ are officially supported by the latest version of golangci-lint (>= 1.18.0).`

When I upgraded `golangci-lint` to `v1.21.0` I didn't see any errors running `hack/linter.sh` (which is what travis calls to run `golangci-lint`

**Comment by cvgw** [comment]
@tejal29 can we remove `hack/dep.sh` as part of this change?

**Comment by vigith** [comment]
should we remove vendor dir since go 1.13 supports module mirroring?

**Comment by tejal29** [comment]
@cvgw yes. We can definitely remove hack/dep.sh as part of this change.

**Comment by tejal29** [comment]
> should we remove vendor dir since go 1.13 supports module mirroring?

removing vendor dir, slows down travis a lot. we shd keep it.

**Comment by cvgw** [comment]
rebased against master

**Pull request merged**
